# Generated by Django 4.2.4 on 2023-08-08 12:18

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("wallets", "0002_alter_wallet_balance_alter_wallet_name_transaction"),
    ]

    operations = [
        migrations.DeleteModel(
            name="Transaction",
        ),
    ]
