# Generated by Django 4.2.4 on 2023-08-08 15:11

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("wallets", "0003_delete_transaction"),
    ]

    operations = [
        migrations.AlterField(
            model_name="wallet",
            name="currency",
            field=models.CharField(
                choices=[("USD", "USD"), ("EUR", "EUR"), ("GBP", "GBP")],
                default="USD",
                max_length=3,
            ),
        ),
        migrations.AlterField(
            model_name="wallet",
            name="id",
            field=models.BigAutoField(
                auto_created=True,
                primary_key=True,
                serialize=False,
                verbose_name="ID",
            ),
        ),
        migrations.AlterField(
            model_name="wallet",
            name="type",
            field=models.CharField(
                choices=[("visa", "Visa"), ("mastercard", "Mastercard")],
                default="visa",
                max_length=10,
            ),
        ),
    ]
