# Generated by Django 4.2.4 on 2023-08-14 09:10

from decimal import Decimal
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("wallets", "0004_alter_wallet_currency_alter_wallet_id_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="wallet",
            name="balance",
            field=models.DecimalField(
                decimal_places=2,
                default=0.0,
                editable=False,
                max_digits=20,
                validators=[
                    django.core.validators.MinValueValidator(Decimal("0"))
                ],
            ),
        ),
    ]
