# Generated by Django 4.2.4 on 2023-08-09 10:23

from decimal import Decimal
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("transactions", "0002_alter_transaction_commission_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="transaction",
            name="commission",
            field=models.DecimalField(
                decimal_places=2,
                default=0.0,
                editable=False,
                max_digits=20,
                validators=[
                    django.core.validators.MinValueValidator(Decimal("0"))
                ],
            ),
        ),
    ]
