# Generated by Django 4.2.4 on 2023-08-11 10:25

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("transactions", "0003_alter_transaction_commission"),
    ]

    operations = [
        migrations.AlterField(
            model_name="transaction",
            name="status",
            field=models.CharField(
                choices=[("PAID", "Paid"), ("FAILED", "Failed")],
                default="FAILED",
                editable=False,
                max_length=6,
            ),
        ),
    ]
